export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as AboutContact} from './AboutContact'
export {default as Bottoms} from './Bottoms'
export {default as Checkout} from './Checkout'
export {default as Footer} from './Footer'
export {default as OrderHistory} from './OrderHistory'
export {default as Signup} from './Signup'
export {default as SizeChart} from './SizeChart'
export {default as Tops} from './Tops'

